# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Env Prepare
description: 'prepare for building environment'
runs:
  using: "composite"
  steps:
    - name: Setup node
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org

    - name: Environment variables
      shell: bash
      run: |
        env

    - name: Install
      shell: bash
      run: |
        npm i -g pnpm
        npm --version
        pnpm --version
        pnpm i --frozen-lockfile

    - name: ESLint
      shell: bash
      run: |
        pnpm lint